### ISSUE TITLE
Sprite.geometry seems to get cached

### ISSUE THREAD

**Issue by defmech** [rohan-deshpande/three-proton#41]
When creating new Sprite() particles with modified geometry (UV coordinates) the system seems to cache the geometry. Subsequent new particles will use the existing modified geometry. We're using a sprite sheet so need to modify UVs to apply the correct texture to the sprite.

**Comment by rohan-deshpande** [comment]
I think this probably has to do with the pooling but I can’t be sure, do you mind pasting some code? Even better if you can make a quick demo over at [codesandbox.io](https://codesandbox.io) so I can see your exact use case.

**Comment by defmech** [comment]
We've worked around it at moment by updating the material texture's offset and repeat properties instead of updating the geometry UVs.

Apologies but I don't have the time to put together a demo at the moment.

**Comment by rohan-deshpande** [comment]
Hmm that kind of sounds like the right thing to do for sprite sheets to me actually. But yeah, can’t say too much without seeing code. Glad you got it sorted for now!
